kind: pipeline
name: Build

steps:
- name: build
  image: node
  environment:
    VITE_APPWRITE_PROJECT_ID:
      from_secret: VITE_APPWRITE_PROJECT_ID
    VITE_APPWRITE_API_ENDPOINT:
      from_secret: VITE_APPWRITE_API_ENDPOINT
    VITE_APPWRITE_COLLECTION_ID:
      from_secret: VITE_APPWRITE_COLLECTION_ID
    VITE_APPWRITE_USER_ICON_BUCKET_ID:
      from_secret: VITE_APPWRITE_USER_ICON_BUCKET_ID
  volumes:
  - name: deploy
    path: /
  commands:
  - npm install
  - pwd
  # - npm run build

- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    avatar_url:
      from_secret: discord_avatar_url

volumes:
- name: deploy
  host:
    path: /deploy