kind: pipeline
type: docker
name: Build

workspace:
  path: /app

steps:
- name: build
  image: node
  environment:
    VITE_APPWRITE_PROJECT_ID:
      from_secret: VITE_APPWRITE_PROJECT_ID
    VITE_APPWRITE_API_ENDPOINT:
      from_secret: VITE_APPWRITE_API_ENDPOINT
    VITE_APPWRITE_COLLECTION_ID:
      from_secret: VITE_APPWRITE_COLLECTION_ID
    VITE_APPWRITE_USER_ICON_BUCKET_ID:
      from_secret: VITE_APPWRITE_USER_ICON_BUCKET_ID
  commands:
  - npm install
  - npm run build
  - ls -la
  - ls /app/dist

- name: write-settings
  image: node
  commands:
  - echo "TODO"

- name: deploy
  image: node
  volumes:
  - name: deploy
    path: /app/deploy
  commands:
  - ls /app
  - ls /app/deploy
  - mv /app/dist/* /app/deploy

- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    avatar_url:
      from_secret: discord_avatar_url


volumes:
- name: deploy
  path:
    host:
      from_secret: deploy_dir